spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/devices?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: prod_user
    password: prod_secret
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com.example.devices: INFO
